[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rust-test = "0.1.0"

[dependencies]
termcolor = "1.2.0"
rand = "0.8.5"
ansi_term = "0.12.1"
term_size = "0.1.0"

